# Generated by Django 5.0.3 on 2024-03-21 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('miqdori', models.IntegerField()),
                ('chegirma_foizi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chegirma_muddati', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chegirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chegirma_foizi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chegirma_muddati', models.DateField()),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoop.mahsulot')),
            ],
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('buyurtma_id', models.AutoField(primary_key=True, serialize=False)),
                ('miqdori', models.IntegerField()),
                ('chegirma_foizi', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('chegirma_muddati', models.DateField(blank=True)),
                ('summa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qabul_sana', models.DateField()),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoop.mahsulot')),
            ],
        ),
    ]
